image: Visual Studio 2017
 
environment:
  MSVC_DEFAULT_OPTIONS: ON
  CHOCOKEY:
    secure: FWFxhYDT9wCj3hnjuM2IPZCYe4GssEuxD3UCynfUhzJL0I/3Fjbjeab0JYO6BmPz

configuration:
  - Release

install:
  - cmd: set ARCH=x86
  - cmd: choco install go-msi
  - cmd: set PATH=C:\Program Files\go-msi\;%PATH%
  - cmd: set PATH=C:\Program Files (x86)\WiX Toolset v3.11\bin;%PATH%
    
before_build:
  - cmd: if %ARCH%==x86 set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - cmd: if %ARCH%==x64 set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
  - cmd: set FILENAMES_PREFIX=%APPVEYOR_PROJECT_NAME%-%ARCH%-%APPVEYOR_BUILD_VERSION%
  - cmd: md build
  - cmd: cd build

build_script:
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" ../src
  - cmd: cmake --build . --config %CONFIGURATION%
  - cmd: cd .. 
  - cmd: go-msi make
      --path msi-creation-data.json
      --version %APPVEYOR_BUILD_VERSION%
      --msi build/msi/%FILENAMES_PREFIX%.msi

  - cmd: go-msi choco
      --path msi-creation-data.json
      --version %APPVEYOR_BUILD_VERSION%
      --input build/msi/%FILENAMES_PREFIX%.msi
      --out build/nupkg
      
artifacts:
  - path: "build/msi/%FILENAMES_PREFIX%.msi"
  
deploy:
  - provider: BinTray
    username: solvingj
    api_key:
       secure: ebQ+n7tSPtW4Ou+GAbqv5pQZDtSMXq5xNGNvoGH7651g7bY0tOK5st1LWLo9Kept
    subject: solvingj
    repo: public-generic
    package: "%APPVEYOR_PROJECT_NAME%"
    version: "%APPVEYOR_BUILD_VERSION%"
    override: true
    publish: true
    explode: false
    
    
after_deploy:
  - cmd: choco push -k="'%CHOCOKEY%'" build/nupkg/%APPVEYOR_PROJECT_NAME%.%APPVEYOR_BUILD_VERSION%.nupkg
