image: Visual Studio 2017
 
environment:
  MSVC_DEFAULT_OPTIONS: ON

configuration:
  - Release

install:
  - cmd: set ARCH=x86
  - cmd: choco install go-msi
  - cmd: set PATH=C:\Program Files\go-msi\;%PATH%
    
before_build:
  - cmd: if %ARCH%==x86 set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - cmd: if %ARCH%==x64 set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
  - cmd: set FILENAMES_PREFIX=%APPVEYOR_PROJECT_NAME%-%ARCH%-%APPVEYOR_BUILD_VERSION%
  - cmd: md build
  - cmd: cd build

build_script:
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" ../src
  - cmd: cmake --build . --config %CONFIGURATION%
  - cmd: cd ..
  - cmd: go-msi make --path msi-creation-data.json --version %APPVEYOR_BUILD_VERSION% --msi %APPVEYOR_PROJECT_NAME%-%ARCH%-%APPVEYOR_BUILD_VERSION%.msi
 
artifacts:
  - path: "build/$(CONFIGURATION)/$(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_BUILD_VERSION).msi"
  
deploy:
  - provider: BinTray
    username: solvingj
    api_key:
       secure: ebQ+n7tSPtW4Ou+GAbqv5pQZDtSMXq5xNGNvoGH7651g7bY0tOK5st1LWLo9Kept
    override: true
    subject: solvingj
    repo: public-generic
    package: "%APPVEYOR_PROJECT_NAME%"
    version: "%APPVEYOR_BUILD_VERSION%"
    publish: true
    explode: false
    
    
#after_deploy:
#  - cmd: choco push -k="'%CHOCOKEY%'" build/$(CONFIGURATION)/%APPVEYOR_PROJECT_NAME%-%ARCH%.%APPVEYOR_REPO_TAG_NAME%.nupkg
