image: Visual Studio 2017
 
environment:
  MSVC_DEFAULT_OPTIONS : ON
  PKG_VERSION : 0.0.1
  BINTRAY_REPO_MSI : "public-msi"
  BINTRAY_REPO_NUGET : "public-nuget"
  BINTRAY_USER : "solvingj"
  BINTRAY_SUBJECT : "solvingj"
  BINTRAY_KEY: 
    secure: ebQ+n7tSPtW4Ou+GAbqv5pQZDtSMXq5xNGNvoGH7651g7bY0tOK5st1LWLo9Kept
  CHOCO_KEY:
    secure: ywiaCdFML29M2/iL/v1G36wPZSk4uIRcfJP56J7rDVPuQDwweuGqHZQPFWY8ZgbJ  
  matrix:
    - ARCH: x86
    - ARCH: x64

configuration:
  - Release

install: python ci/appveyor_pipeline.py -step_name install
before_build: python ci/appveyor_pipeline.py -step_name before_build
build_script: python ci/appveyor_pipeline.py -step_name build_script
after_build: python ci/appveyor_pipeline.py -step_name after_build
deploy_script: python ci/appveyor_pipeline.py -step_name deploy_script