version: 0.0.2
branches:
  only:
    - master

image: Visual Studio 2017
 
environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_63_0

configuration:
  - Release

before_build:
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "Visual Studio 15 2017" ../src

build_script:
  - cmd: msbuild ALL_BUILD.vcxproj /p:Configuration=%CONFIGURATION%

artifacts:
  - path: "build/$(CONFIGURATION)/$(APPVEYOR_PROJECT_NAME).exe"
  
deploy:
  - provider: BinTray
    username: solvingj
    api_key:
       secure: ebQ+n7tSPtW4Ou+GAbqv5pQZDtSMXq5xNGNvoGH7651g7bY0tOK5st1LWLo9Kept
    override: true
    subject: solvingj
    repo: public-generic
    package: "%APPVEYOR_PROJECT_NAME%"
    version: "0.0.2"
    publish: true
    explode: false