version: 0.0.1
branches:
  only:
    - master
 
skip_non_tags: true

image: Visual Studio 2017
 
environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_63_0

configuration:
    - Release

before_build:
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME="Visual Studio 15 2017"
  - cmd: if "%platform%"=="x64" set CMAKE_GENERATOR_NAME="Visual Studio 15 2017 Win64"
  - cmd: cmake -G %CMAKE_GENERATOR_NAME% ../src

build_script:
  - cmd: msbuild ALL_BUILD.vcxproj /p:Configuration=%CONFIGURATION%

deploy:
  - provider: BinTray
    username: solvingj
    api_key:
       secure: ebQ+n7tSPtW4Ou+GAbqv5pQZDtSMXq5xNGNvoGH7651g7bY0tOK5st1LWLo9Kept
    override: true
    subject: solvingj
    repo: public-generic
    package: "%APPVEYOR_PROJECT_NAME%"
    version: "%APPVEYOR_REPO_TAG_NAME%"
    publish: true
    explode: false