sudo: required
language: cpp

services:
- docker

compiler:
- gcc

os:
- linux

env:
  matrix:
    # - PKG_TYPE=DEB ARCH="all"
    - PKG_TYPE=DEB ARCH="amd64"
    # - PKG_TYPE=DEB ARCH="i386"
    # - PKG_TYPE=RPM ARCH="x86_64"
    # - PKG_TYPE=RPM ARCH="i386"

  global:
  #Eventually change to  PACKAGE_VERSION=${TRAVIS_TAG}
    - REPO_NAME=${TRAVIS_REPO_SLUG#*/}
    - PKG_VERSION="0.0.1"
    
before_install: sudo python ci/travis/01_before_install.py
install: sudo python ci/travis/02_install.py
before_script: mkdir build && cd build && cmake ../src && cmake --build . --config release && cd ..
script: python ci/travis/04_script.py
after_script: cd ${TRAVIS_BUILD_DIR}
  
deploy:
  - provider: bintray
    file: deb-publish-data.json
    version: 
      name: ${PKG_VERSION}
    on:
      all_branches: true
      condition: ${PKG_TYPE} = "DEB"
    skip_cleanup: true
    user: solvingj
    key: 
      secure: "S/5a2/n2tfTid37QOmigtA5vc54mj1d54O3twYOgiGoN2IUHkwYWR0Wjzng/6/H2K+wAZo8Lyn7Mx/rZDkZttDHvmKXxEayeW9yyJRXnfFyXCI0kCoB0PkiaFMHScKc1JgloVGsdy35fq3k8YCfofY6FAxejT0woXQ6wFceUBcQm1VaY8/vW8j5umXPt1LzRXPiUEblzCC+KMv9YnogKiAc8T7hZCY9vK1KYlJBrdcP79udU1RnFrvS4lnMZCIDw5qcPOXRZN9lzdqQe5frsHCwOs75AaV2Bnrw5A29/Piv/oRyv/VJ85SXDJwzOmf4cHymdfrCYeT/Zkg7eYuUT6QV4ix+i/5cDsz3N82zigVZOJ+wqaEHTmqj4WbJdo8lLsGj0uCsZo5HDtPUJWgi5+w5k/ZI0HX6PTdwHb1PmCDx06vMXWD5SKwfwK/T49yjaY3vK6r7ppQvr+wQcEolUzDHZz+vhlwq18Xj5oekVbQZ+cg7vzyScFS5LUVdCkpvVd+3MkxTkG2AnyUtvp3TjmTCoOUGM9nfJxZu0dbqVyWRhIbV+W3TjsyVgL4BUedcPVLggtVYEe74HK1tkPe1ogEcRD42b6qo4kX641QiSWh+aH5LIRvbQNuRmJ8yTGb8NUI7XNZ2i2qb13cPbChTVrgy6G+9l6G0AFdok9xTxRmI="
  # - provider: bintray
    # file: rpm-publish-data.json
    # version: 
      # name: ${PKG_VERSION}
    # on:
      # all_branches: true
      # condition: ${PKG_TYPE} = "RPM"
    # skip_cleanup: true
    # user: solvingj
    # key: 
      # secure: "S/5a2/n2tfTid37QOmigtA5vc54mj1d54O3twYOgiGoN2IUHkwYWR0Wjzng/6/H2K+wAZo8Lyn7Mx/rZDkZttDHvmKXxEayeW9yyJRXnfFyXCI0kCoB0PkiaFMHScKc1JgloVGsdy35fq3k8YCfofY6FAxejT0woXQ6wFceUBcQm1VaY8/vW8j5umXPt1LzRXPiUEblzCC+KMv9YnogKiAc8T7hZCY9vK1KYlJBrdcP79udU1RnFrvS4lnMZCIDw5qcPOXRZN9lzdqQe5frsHCwOs75AaV2Bnrw5A29/Piv/oRyv/VJ85SXDJwzOmf4cHymdfrCYeT/Zkg7eYuUT6QV4ix+i/5cDsz3N82zigVZOJ+wqaEHTmqj4WbJdo8lLsGj0uCsZo5HDtPUJWgi5+w5k/ZI0HX6PTdwHb1PmCDx06vMXWD5SKwfwK/T49yjaY3vK6r7ppQvr+wQcEolUzDHZz+vhlwq18Xj5oekVbQZ+cg7vzyScFS5LUVdCkpvVd+3MkxTkG2AnyUtvp3TjmTCoOUGM9nfJxZu0dbqVyWRhIbV+W3TjsyVgL4BUedcPVLggtVYEe74HK1tkPe1ogEcRD42b6qo4kX641QiSWh+aH5LIRvbQNuRmJ8yTGb8NUI7XNZ2i2qb13cPbChTVrgy6G+9l6G0AFdok9xTxRmI="
    