sudo: required
language: cpp

services:
- docker

compiler:
- gcc

os:
- linux

env:
  matrix:
    # - PKG_TYPE=DEB ARCH="all"
    - PKG_TYPE=DEB ARCH="amd64"
    # - PKG_TYPE=DEB ARCH="i386"
    # - PKG_TYPE=RPM ARCH="x86_64"
    # - PKG_TYPE=RPM ARCH="i386"

  global:
  #Eventually change to  PACKAGE_VERSION=${TRAVIS_TAG}
    - REPO_NAME=${TRAVIS_REPO_SLUG#*/}
    - PKG_VERSION="0.0.1"
    
before_install: sudo python ci/travis_pipeline.py -step_name before_install
install: sudo python ci/travis_pipeline.py -step_name install
script: sudo python ci/travis_pipeline.py -step_name script
before_deploy: sudo python ci/travis_pipeline.py -step_name before_deploy
after_deploy: sudo python ci/travis_pipeline.py -step_name deploy
