sudo: required
language: cpp
services:
- docker
compiler:
- gcc
os:
- linux
env:
  matrix:
  - ARCH="amd64"
  - ARCH="i386"
  global:
  - GIT_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
  - PKG_VERSION=${TRAVIS_TAG}
  - BINTRAY_REPO_DEB="public-deb"
  - BINTRAY_REPO_RPM="public-rpm"
  - BINTRAY_REPO_TARGZ="public-targz"
  - BINTRAY_REPO_CONAN="public-conan"
  - BINTRAY_SUBJECT=solvingj

before_install: sudo python ci/travis_pipeline.py -step_name before_install
install: sudo python ci/travis_pipeline.py -step_name install
script: sudo python ci/travis_pipeline.py -step_name script
after_success: sudo python ci/travis_pipeline.py -step_name after_success
